version: "3.1"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "1.17-bullseye"
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    user: vscode